{"name": "Проверка, что при авторизации под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Проверка статус кода = 404 и сообщения Учетная запись не найдена при неверном логине курьера", "steps": [{"name": "Логин курьера в системе", "status": "passed", "start": 1721133148266, "stop": 1721133148377}, {"name": "Проверка статус кода = 404 и сообщения \"Учетная запись не найдена\"", "status": "passed", "start": 1721133148377, "stop": 1721133148377}], "start": 1721133148266, "stop": 1721133148377, "uuid": "77230aa8-70ab-4fa6-85f2-69c84a9e660a", "historyId": "c6bd9b0145eea4b63726aaa37b7dc1c3", "testCaseId": "c6bd9b0145eea4b63726aaa37b7dc1c3", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_login_incorrect_values_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-DSB2CVA"}, {"name": "thread", "value": "9512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}